server:
  port: 8781


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: orde-service
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 0.1
#  redis:
#    database:   #默认 0
#    host:    #链接地址
#    port:    # 端口号
#    timeout: 2000  #超时时间
#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
       connectTimeout: 4000  #超时 时间最好不要超过两秒
       readTimeout: 4000

#自定义负载均衡策略
#product-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
