server:
  port: 9100

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
           uri: https://gitee.com/helloAccept/config-cloud
           username: 13561066995
           password: shun321.
           timeout: 5
           default-label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/